version: '3'

volumes:
  mariadb:
    driver: local

networks:
  db:
    driver: bridge

services:
  mariadb:
    image: mariadb:10.7.8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_dev
      MYSQL_USER:  discord
      MYSQL_PASSWORD: discord
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      db:

  phpmyadmin:
    image: phpmyadmin
    restart: always
    expose:
      - "8080"
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    networks:
      db: